### PR TITLE
Added D0 Wakeup Character to UI form

### PR DESCRIPTION
**Pull request by klein0r**

### CODE REVIEW

**Comment by coolchip** [comment]
Thank you very much for your help. I will build a new version and publish it to npm.

**Comment by klein0r** [comment]
Thanks for the insanely fast response 🥇

**Comment by klein0r** [comment]
The version on https://flows.nodered.org/node/node-red-contrib-smartmeter is still the 0.1.2 - can you update that version too?

**Comment by coolchip** [comment]
Packages for Node-RED are provided by NPM and v0.2.0 is published to NPM. I don't understand, why it is not visible to Node-RED Library.
Anyway Idea?

**Comment by coolchip** [comment]
Seems to be a problem on NPM itself.
https://github.com/npm/registry/issues/366

**Pull request merged**
